### ISSUE TITLE
Issues about the dataset details and extracting I3D features

### ISSUE THREAD

**Issue by wyyy04** [KPeng9510/RelaMiX#1]
Thanks for your excellent work! However, I find some difficulties in reproducing the code. I look forward to your reply and answer！ 

1. ToyotSmartHome dataset
 I would like to ask if the ToyotSmartHome dataset used in the article is a **trimmed** or **untrimmed** version. Whether the official I3D features are used？

2. Extracting I3D features
It is pointed out in the paper and instructions that the frame-level I3D features of each video need to be extracted before training and testing the network, but I did not find the relevant code in the repository. Instead, the code in [dataset_preparation] uses the **C3D** network and **ResNet** to extract video frame features. Could you please provide the code for extracting features with **I3D**? 

3. calculate_statistics_trainset_X.py
Several functions in these python files are not defined. 
For example, in calculate_statistics_trainset_hmdb_ucf.py
Line 257: `prec1 = validate(val_loader, model, criterion, num_class, epoch, val_file)`
Line 264: `val_short_file.write('%.3f\n' % prec1)`
Line 272: `val_best_file.write('%.3f\n' % best_prec1)`
validate/val_short_file/val_best_file are not defined. Please check it. 

These are my issues, and I'm looking forward to your reply. Thanks for your help!

**Comment by KPeng9510** [comment]
Hi,

Thank you for your interests on our work. 

1. Our work is based on the trimmed ToyotaSmartHome. We do not use the official features.

2. Please refer to this repo for the feature extraction, we follow the same way with theirs. https://github.com/ldkong1205/TranSVAE

3. you could delete those lines which are not useful, we only use the stored pkl files.
